addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.1.0")
addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.7")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"     % "0.6.22")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "2.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "1.5.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.3.3")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "1.0.0")
