addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.0.0")
addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"     % "0.6.11")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "0.5.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "1.3.5")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.2.5")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("com.github.alexarchambault" %% "sbt-ammonite" % "0.1.2")
// addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.5.1")